linters: #enable extra linters in addition to the default
  enable:
    - gofmt
    - goimports
    - misspell
    - gosimple
    - copyloopvar
    - nilerr
    - unconvert
    - unparam
    - prealloc
    - perfsprint

run:
  timeout: 5m

issues:
  exclude-rules:
    - source: "^func Test"
      linters:
        - funlen
    - linters:
        - typecheck
      text: "has no field or method"
