# .github/workflows/build-release.yml
name: Build release

on: workflow_call

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build artifacts
    runs-on: ubuntu-latest
    container:
      image: anibaldeboni/trimui-smart-pro-toolchain:latest
      env:
        SS_DEV_ID: ${{ secrets.SS_DEV_ID }}
        SS_DEV_PASSWORD: ${{ secrets.SS_DEV_PASSWORD }}
    steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Build package
          run: make

        - name: Upload assets
          uses: softprops/action-gh-release@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          if: ${{startsWith(github.ref, 'refs/tags/') }}
          with:
            files: ./ScreechApp/ScreechApp.zip
        