name: Code quality

on: workflow_call

permissions:
  contents: read

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false

      - name: Install SDL2
        run: sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          skip-cache: true
