name: Master branch pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  actions: read
  contents: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
