# .github/workflows/release.yml
name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    name: Build artifacts
    runs-on: ubuntu-latest
    container:
      image: anibaldeboni/trimui-smart-pro-toolchain:latest
      env:
        SS_DEV_ID: ${{ secrets.SS_DEV_ID }}
        SS_DEV_PASSWORD: ${{ secrets.SS_DEV_PASSWORD }}
    steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Run the build process
          run: make

        - name: upload assets to release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          if: ${{startsWith(github.ref, 'refs/tags/') }}
          with:
            files: ./dist/Screech/ScreechApp.zip
        