name: Code quality

on: workflow_call

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false

      - name: Install SDL2
        run: sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev

      - name: Download dependencies
        run: go mod download -x

      - name: Run tests
        run: make test
